version: '3.4'

services:
 db:
  image: uai-flay-db
  command: mysqld --default-authentication-plugin=mysql_native_password
  restart: always
  build:
    context: .
    dockerfile: db/Dockerfile
  environment: 
    TZ: America/Sao_Paulo
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
    MYSQL_DATABASE: uaiflydb
  ports:
   - 3308:3306
  networks: 
   - uai-fly-network

 uai-flay:
  image: uai-fly
  build:
   context: .
   dockerfile: Api.Application/Dockerfile
  environment: 
    TZ: America/Sao_Paulo
    ASPNETCORE_ENVIRONMENT: Production
  ports:
   - 44300:80
  depends_on:
   - db
  networks: 
   - uai-fly-network
 
networks:
  uai-fly-network:
    driver: bridge
