export const carMakes = [
    { name: 'Toyota', code: 'TOY' },
    { name: 'Ford', code: 'FRD' },
    { name: 'Chevrolet', code: 'CHEV' },
    { name: 'BMW', code: 'BMW' },
    { name: 'Mercedes-Benz', code: 'MB' },
    { name: 'Honda', code: 'HON' },
    { name: 'Audi', code: 'AUD' },
    { name: 'Nissan', code: 'NIS' },
    { name: 'Hyundai', code: 'HYD' },
    { name: 'Volkswagen', code: 'VW' },
    { name: 'Kia', code: 'KIA' },
    { name: 'Peugeot', code: 'PEU' },
    { name: 'Mazda', code: 'MAZ' },
    { name: 'Jeep', code: 'JEE' },
    { name: 'Subaru', code: 'SUB' },
    { name: 'Chrysler', code: 'CHR' },
    { name: 'Fiat', code: 'FIA' },
    { name: 'Land Rover', code: 'LR' },
    { name: 'Porsche', code: 'POR' },
    { name: 'Ferrari', code: 'FER' },
    { name: 'Lexus', code: 'LEX' },
    { name: 'Tesla', code: 'TES' },
    { name: 'Jaguar', code: 'JAG' },
    { name: 'Mitsubishi', code: 'MIT' },
    { name: 'Buick', code: 'BUC' },
    { name: 'Lincoln', code: 'LIN' },
    { name: 'GMC', code: 'GMC' },
    { name: 'Acura', code: 'ACU' },
    { name: 'Infiniti', code: 'INF' },
    { name: 'Alfa Romeo', code: 'ALF' },
    { name: 'Volvo', code: 'VOL' }
  ];