export interface CarModel {
  name: string;
  code: string;
}

export interface CarModels {
  [key: string]: CarModel[];  // The key is the car brand code, and the value is an array of CarModel
}

export const carModels : CarModels  = {
    TOY: [
      { name: 'Corolla', code: 'COR' },
      { name: 'Camry', code: 'CAM' },
      { name: 'Hilux', code: 'HIL' },
      { name: 'RAV4', code: 'RAV' },
      { name: 'Land Cruiser', code: 'LC' },
      { name: 'Tacoma', code: 'TAC' },
      { name: 'Avalon', code: 'AVA' },
      { name: 'Sienna', code: 'SIE' },
    ],
    FRD: [
      { name: 'F-150', code: 'F150' },
      { name: 'Mustang', code: 'MUS' },
      { name: 'Explorer', code: 'EXP' },
      { name: 'Focus', code: 'FOC' },
      { name: 'Escape', code: 'ESC' },
      { name: 'Edge', code: 'EDG' },
      { name: 'Ranger', code: 'RAN' },
      { name: 'Expedition', code: 'EXP' },
    ],
    CHEV: [
      { name: 'Cruze', code: 'CRU' },
      { name: 'Impala', code: 'IMP' },
      { name: 'Camaro', code: 'CAM' },
      { name: 'Equinox', code: 'EQU' },
      { name: 'Silverado', code: 'SIL' },
      { name: 'Traverse', code: 'TRA' },
      { name: 'Malibu', code: 'MAL' },
      { name: 'Tahoe', code: 'TAH' },
    ],
    BMW: [
      { name: '3 Series', code: '3S' },
      { name: 'X5', code: 'X5' },
      { name: '5 Series', code: '5S' },
      { name: 'M3', code: 'M3' },
      { name: '7 Series', code: '7S' },
      { name: 'X3', code: 'X3' },
      { name: 'X4', code: 'X4' },
      { name: 'M4', code: 'M4' },
    ],
    MB: [
      { name: 'C-Class', code: 'C' },
      { name: 'E-Class', code: 'E' },
      { name: 'S-Class', code: 'S' },
      { name: 'GLC', code: 'GLC' },
      { name: 'GLE', code: 'GLE' },
      { name: 'GLS', code: 'GLS' },
      { name: 'A-Class', code: 'A' },
      { name: 'CLA', code: 'CLA' },
    ],
    HON: [
      { name: 'Civic', code: 'CIV' },
      { name: 'Accord', code: 'ACC' },
      { name: 'CR-V', code: 'CRV' },
      { name: 'Pilot', code: 'PIL' },
      { name: 'Odyssey', code: 'ODY' },
      { name: 'HR-V', code: 'HRV' },
      { name: 'Fit', code: 'FIT' },
      { name: 'Ridgeline', code: 'RID' },
    ],
    AUD: [
      { name: 'A3', code: 'A3' },
      { name: 'A4', code: 'A4' },
      { name: 'A6', code: 'A6' },
      { name: 'Q5', code: 'Q5' },
      { name: 'Q7', code: 'Q7' },
      { name: 'Q8', code: 'Q8' },
      { name: 'R8', code: 'R8' },
      { name: 'S3', code: 'S3' },
    ],
    NIS: [
      { name: 'Altima', code: 'ALT' },
      { name: 'Maxima', code: 'MAX' },
      { name: '370Z', code: '370Z' },
      { name: 'Pathfinder', code: 'PAT' },
      { name: 'Murano', code: 'MUR' },
      { name: 'Rogue', code: 'ROG' },
      { name: 'Leaf', code: 'LEA' },
      { name: 'Frontier', code: 'FRO' },
    ],
    HYD: [
      { name: 'Elantra', code: 'ELA' },
      { name: 'Tucson', code: 'TUC' },
      { name: 'Sonata', code: 'SON' },
      { name: 'Santa Fe', code: 'SFE' },
      { name: 'Kona', code: 'KON' },
      { name: 'Palisade', code: 'PAL' },
      { name: 'Ioniq', code: 'ION' },
      { name: 'Venue', code: 'VEN' },
    ],
    VW: [
      { name: 'Golf', code: 'GOL' },
      { name: 'Jetta', code: 'JET' },
      { name: 'Passat', code: 'PAS' },
      { name: 'Tiguan', code: 'TIG' },
      { name: 'Atlas', code: 'ATL' },
      { name: 'ID.4', code: 'ID4' },
      { name: 'Beetle', code: 'BEET' },
      { name: 'Arteon', code: 'ART' },
    ],
    KIA: [
      { name: 'Optima', code: 'OPT' },
      { name: 'Sportage', code: 'SPO' },
      { name: 'Soul', code: 'SOU' },
      { name: 'Seltos', code: 'SEL' },
      { name: 'Telluride', code: 'TEL' },
      { name: 'Stinger', code: 'STI' },
      { name: 'Forte', code: 'FOR' },
      { name: 'Cadenza', code: 'CAD' },
    ],
    PEU: [
      { name: '208', code: '208' },
      { name: '3008', code: '3008' },
      { name: '5008', code: '5008' },
      { name: '508', code: '508' },
      { name: 'Partner', code: 'PAR' },
      { name: 'Expert', code: 'EXP' },
      { name: 'Boxer', code: 'BOX' },
      { name: 'Rifter', code: 'RIF' },
    ],
    MAZ: [
      { name: 'Mazda3', code: 'MAZ3' },
      { name: 'Mazda6', code: 'MAZ6' },
      { name: 'CX-5', code: 'CX5' },
      { name: 'CX-9', code: 'CX9' },
      { name: 'MX-5 Miata', code: 'MX5' },
      { name: 'CX-50', code: 'CX50' },
      { name: 'Mazda2', code: 'MAZ2' },
      { name: 'Mazda3 Hatchback', code: 'MAZ3HB' },
    ],
    JEE: [
      { name: 'Cherokee', code: 'CHER' },
      { name: 'Grand Cherokee', code: 'GRANDCHER' },
      { name: 'Wrangler', code: 'WRAN' },
      { name: 'Renegade', code: 'RENE' },
      { name: 'Compass', code: 'COMP' },
      { name: 'Gladiator', code: 'GLAD' },
      { name: 'Wagoneer', code: 'WAG' },
    ],
    SUB: [
      { name: 'Outback', code: 'OUT' },
      { name: 'Forester', code: 'FOR' },
      { name: 'Impreza', code: 'IMP' },
      { name: 'Crosstrek', code: 'CRO' },
      { name: 'Ascent', code: 'ASC' },
      { name: 'Legacy', code: 'LEG' },
    ],
    CHR: [
      { name: 'Pacifica', code: 'PAC' },
      { name: 'Chrysler 300', code: 'CH300' },
      { name: 'Voyager', code: 'VOY' },
    ],
    FIA: [
      { name: 'Panda', code: 'PAN' },
      { name: '500', code: '500' },
      { name: 'Tipo', code: 'TIP' },
      { name: 'Ducato', code: 'DUC' },
    ],
    LR: [
      { name: 'Range Rover', code: 'RR' },
      { name: 'Discovery', code: 'DIS' },
      { name: 'Defender', code: 'DEF' },
      { name: 'Evoque', code: 'EVO' },
    ],
    POR: [
      { name: '911', code: '911' },
      { name: 'Cayenne', code: 'CAY' },
      { name: 'Macan', code: 'MAC' },
      { name: 'Panamera', code: 'PAN' },
    ],
    FER: [
      { name: '488', code: '488' },
      { name: 'Portofino', code: 'POR' },
      { name: 'Roma', code: 'ROM' },
    ],
    LEX: [
      { name: 'IS', code: 'IS' },
      { name: 'ES', code: 'ES' },
      { name: 'GS', code: 'GS' },
      { name: 'RX', code: 'RX' },
      { name: 'NX', code: 'NX' },
      { name: 'LX', code: 'LX' },
      { name: 'UX', code: 'UX' },
    ],
    TES: [
      { name: 'Model S', code: 'S' },
      { name: 'Model 3', code: '3' },
      { name: 'Model X', code: 'X' },
      { name: 'Model Y', code: 'Y' },
    ],
    JAG: [
      { name: 'XE', code: 'XE' },
      { name: 'XF', code: 'XF' },
      { name: 'XJ', code: 'XJ' },
      { name: 'F-Type', code: 'FTYPE' },
    ],
  };
  