# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - uaifly2

on:
  push:
    branches:
      - feature/finish-tests
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4  # Atualizado para v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js version
        uses: actions/setup-node@v4  # Atualizado para v4
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install
        working-directory: ./frontend

      - name: npm build
        run: npm run build --if-present
        working-directory: ./frontend

      - name: npm test
        run: npm run test --if-present
        working-directory: ./frontend

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Create zip for artifact
        run: tar -czf artifacts/frontend.tar.gz -C frontend .
        shell: bash

      - name: List files after creating artifact
        run: Get-ChildItem -Force artifacts

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: node-app
          path: artifacts/frontend.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4  # Atualizado para v4
        with:
          name: node-app
          path: artifacts

      - name: List files for debugging
        run: ls -la

      - name: List files in artifacts directory for debugging
        run: ls -la artifacts

      - name: Verify artifact presence
        run: test -f artifacts/frontend.tar.gz || { echo "Artifact not found"; exit 1; }

      - name: Unzip artifact
        run: |
          mkdir -p frontend
          tar -xzf artifacts/frontend.tar.gz -C frontend
        shell: bash

      - name: 'Login to Azure'
        uses: azure/login@v2  # Atualizado para v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'uaifly'
          slot-name: 'production'
          package: frontend
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_855151956ffd48898ed8ac90c7324da7 }}